\contentsline {lstlisting}{\numberline {B.1}{\ignorespaces tinyml\_pipeline.py}}{186}{lstlisting.Alph2.1}%
\contentsline {lstlisting}{\numberline {B.2}{\ignorespaces classification\_benchmark.py}}{195}{lstlisting.Alph2.2}%
\contentsline {lstlisting}{\numberline {B.3}{\ignorespaces regression\_benchmark.py}}{198}{lstlisting.Alph2.3}%
\contentsline {lstlisting}{\numberline {B.4}{\ignorespaces models\_classification.py}}{201}{lstlisting.Alph2.4}%
\contentsline {lstlisting}{\numberline {B.5}{\ignorespaces models\_regression.py}}{205}{lstlisting.Alph2.5}%
\contentsline {lstlisting}{\numberline {B.6}{\ignorespaces onnx\_wrapper.py}}{209}{lstlisting.Alph2.6}%
\contentsline {lstlisting}{\numberline {B.7}{\ignorespaces pytorch\_wrapper.py}}{227}{lstlisting.Alph2.7}%
\contentsline {lstlisting}{\numberline {B.8}{\ignorespaces tflite\_wrapper.py}}{241}{lstlisting.Alph2.8}%
\contentsline {lstlisting}{\numberline {B.9}{\ignorespaces datasets\_classification.py}}{257}{lstlisting.Alph2.9}%
\contentsline {lstlisting}{\numberline {B.10}{\ignorespaces datasets\_regression.py}}{257}{lstlisting.Alph2.10}%
\contentsline {lstlisting}{\numberline {B.14}{\ignorespaces load\_iris.py}}{261}{lstlisting.Alph2.14}%
\contentsline {lstlisting}{\numberline {B.16}{\ignorespaces load\_mnist.py}}{263}{lstlisting.Alph2.16}%
\contentsline {lstlisting}{\numberline {B.19}{\ignorespaces load\_abalone.py}}{266}{lstlisting.Alph2.19}%
\contentsline {lstlisting}{\numberline {B.20}{\ignorespaces load\_air\_quality.py}}{267}{lstlisting.Alph2.20}%
\contentsline {lstlisting}{\numberline {B.21}{\ignorespaces load\_energy\_data.py}}{271}{lstlisting.Alph2.21}%
\contentsline {lstlisting}{\numberline {B.22}{\ignorespaces load\_automobile.py}}{272}{lstlisting.Alph2.22}%
\contentsline {lstlisting}{\numberline {B.23}{\ignorespaces load\_bike\_sharing.py}}{274}{lstlisting.Alph2.23}%
\contentsline {lstlisting}{\numberline {B.24}{\ignorespaces load\_communities\_and\_crime.py}}{275}{lstlisting.Alph2.24}%
\contentsline {lstlisting}{\numberline {B.25}{\ignorespaces load\_obesity\_levels.py}}{277}{lstlisting.Alph2.25}%
\contentsline {lstlisting}{\numberline {B.26}{\ignorespaces load\_real\_estate\_valuation.py}}{278}{lstlisting.Alph2.26}%
\contentsline {lstlisting}{\numberline {B.27}{\ignorespaces load\_student\_performance.py}}{279}{lstlisting.Alph2.27}%
\contentsline {lstlisting}{\numberline {B.28}{\ignorespaces load\_wine.py}}{281}{lstlisting.Alph2.28}%
\contentsline {lstlisting}{\numberline {B.29}{\ignorespaces utils.py}}{283}{lstlisting.Alph2.29}%
\contentsline {lstlisting}{\numberline {B.30}{\ignorespaces run\_classification.py}}{284}{lstlisting.Alph2.30}%
\contentsline {lstlisting}{\numberline {B.31}{\ignorespaces run\_regression.py}}{284}{lstlisting.Alph2.31}%
\contentsline {lstlisting}{\numberline {B.32}{\ignorespaces tests\_statistical.py}}{285}{lstlisting.Alph2.32}%
\contentsline {lstlisting}{\numberline {B.33}{\ignorespaces tradeoffs.py}}{298}{lstlisting.Alph2.33}%
